kind: Service
apiVersion: v1
metadata:
  name: iso-service
  namespace: assisted-installer
  labels:
    app: iso-service
spec:
  selector:
    app: iso-service
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  #type: LoadBalancer # For debugging
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iso-service
  namespace: assisted-installer
  labels:
    app: iso-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iso-service
  template:
    metadata:
      labels:
        app: iso-service
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: http-server-files
          mountPath: /usr/share/nginx/html
      volumes:
      - name: http-server-files
        hostPath:
          path: /usr/share/nginx/html
          type: Directory
