apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-ybettan-external-image
spec:
  osImageURL: quay.io/ybettan/rhcos:414.92.202312191338-0
